- src/main/resources/application.yml
* cosmosdb/mongodb idle timeout limit fixed
* cosmosdb/mongodb min pool sizes fixed
> Fix mongo idle timeout (#49)

- src/main/java/it/gov/pagopa/admissibility/dto/onboarding/extra/BirthDate.java
- src/main/java/it/gov/pagopa/admissibility/dto/onboarding/extra/Residence.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/AuthoritiesDataRetrieverServiceImpl.java
- src/test/java/it/gov/pagopa/admissibility/event/consumer/BeneficiaryRuleBuilderConsumerConfigIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/AuthoritiesDataRetrieverServiceImplTest.java
* mocked values not more fixed
> IREER-224 mocked values not more fixed (#76)

- src/main/java/it/gov/pagopa/admissibility/service/onboarding/AuthoritiesDataRetrieverServiceImpl.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/AuthoritiesDataRetrieverServiceImplTest.java
fix bug in isee generation that allows a user not to have a isee
> Idp 842 revisione mock servizio isee

- src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryTestIntegrated.java
- src/test/java/it/gov/pagopa/common/redis/config/EmbeddedRedisTestConfiguration.java
- src/test/java/it/gov/pagopa/common/utils/TestUtils.java
* IDP-1106 findById optimize to be run on cosmosDB
* extending coverage
> feat: IDP-1106 findById optimize to be run on cosmosDB (#150)

- src/test/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceTest.java
- src/test/java/it/gov/pagopa/common/utils/TestUtils.java
* Testing ErrorNotifierService
* relaxing unitTests
> feat: Testing ErrorNotifierService (#153)

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- helm/values.yaml
* IDP-1409 configurableThreadPools
* cannot use separate env var
* configurable
> feat: Idp 1409 configurable thread pools (#172)

- src/main/java/it/gov/pagopa/admissibility/service/commands/operations/DeleteInitiativeServiceImpl.java
**Description**
The purpose of this PR is to allign performance logs for the initiative delete.
**List of changes**
-  Modify info logs
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**
> fix: info log for delete initiative

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/anchore.yml
- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .releaserc.json
- Dockerfile
- helm/Chart.lock
- helm/Chart.yaml
- helm/values.yaml
This PR proposes several devops improvements:
- dependency version pinning
- helm chart upgrade
- new triggers on anchore action
- fix on release action
- new pull request template
- change anchore slack notification template
> fix: [IDP-1697] devops improvements on helm, actions and dockerfile

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/anchore.yml
- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .releaserc.json
- Dockerfile
- helm/Chart.lock
- helm/Chart.yaml
- helm/values.yaml
This pr proposes to promote several devops improvements
> fix: promotion to uat

- .github/CODEOWNERS
- CODEOWNERS
* add codeowners
* move codeowners
> chore: promote to uat - add codeowners

- Dockerfile
> fix: IDP-1760 fix new critical CVE-2022-48174 (#188)

- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeApiRetryable.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
- src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextFilter.java
- src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextHolder.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
IDP-1765 allow mongo RequestRateTooLarge exception always retryable for selected API
> feat: IDP-1765 selected API retryable

- pom.xml
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeApiRetryable.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
- src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextFilter.java
- src/main/java/it/gov/pagopa/common/reactive/web/ReactiveRequestContextHolder.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
> feat: Release dev

- helm/values.yaml
- src/main/java/it/gov/pagopa/admissibility/connector/rest/UserFiscalCodeRestClientImpl.java
- src/main/java/it/gov/pagopa/admissibility/connector/rest/mock/FamilyMockRestClient.java
- src/main/java/it/gov/pagopa/admissibility/connector/rest/mock/FamilyMockRestClientImpl.java
- src/main/java/it/gov/pagopa/admissibility/connector/rest/mock/ResidenceMockRestClient.java
- src/main/java/it/gov/pagopa/admissibility/connector/rest/mock/ResidenceMockRestClientImpl.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/AuthoritiesDataRetrieverServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/pdnd/FamilyDataRetrieverServiceImpl.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/admissibility/BaseIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/connector/event/consumer/BeneficiaryRuleBuilderConsumerConfigIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/connector/event/processor/AdmissibilityProcessorConfigFamilyTest.java
- src/test/java/it/gov/pagopa/admissibility/connector/rest/mock/FamilyMockRestClientImplTest.java
- src/test/java/it/gov/pagopa/admissibility/connector/rest/mock/ResidenceMockRestClientImplTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/AuthoritiesDataRetrieverServiceImplTest.java
- src/test/java/it/gov/pagopa/admissibility/utils/RestTestUtils.java
- src/test/resources/stub/mappings/mock/idpayMockGetFamily.json
- src/test/resources/stub/mappings/mock/idpayMockGetFamilyForMember.json
- src/test/resources/stub/mappings/mock/idpayMockGetFamilyTooManyRequest.json
- src/test/resources/stub/mappings/mock/idpayMockGetResidenceMilano.json
- src/test/resources/stub/mappings/mock/idpayMockGetResidenceTooManyRequest.json
Remove residence and family mock data
- Added connector to idpay-mock
> feat: IDP-1513 initializing refactor mock residence and family unit

- src/main/java/it/gov/pagopa/admissibility/dto/onboarding/EvaluationDTO.java
- src/main/java/it/gov/pagopa/admissibility/dto/onboarding/OnboardingRejectionReason.java
- src/main/java/it/gov/pagopa/admissibility/exception/SkipAlreadyRankingFamilyOnBoardingException.java
- src/main/java/it/gov/pagopa/admissibility/mapper/Onboarding2EvaluationMapper.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/AdmissibilityEvaluatorMediatorServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/family/ExistentFamilyHandlerServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/utils/OnboardingConstants.java
- src/test/java/it/gov/pagopa/admissibility/connector/event/processor/AdmissibilityProcessorConfigFamilyTest.java
- src/test/java/it/gov/pagopa/admissibility/mapper/Onboarding2EvaluationMapperTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/AdmissibilityEvaluatorMediatorServiceImplTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/family/ExistentFamilyHandlerServiceTest.java
Feature for ranking on initiative with family unit.
- Added handler for onboarding ranking family request 
> feat: Idp 1743 sviluppo be - onboarding ranking family request 

- src/test/java/it/gov/pagopa/admissibility/connector/event/processor/AdmissibilityProcessorConfigFamilyTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/AdmissibilityEvaluatorMediatorServiceImplTest.java
- Fix test for ranking family unit
> chore: IDP-1743 fixed family test

- src/test/java/it/gov/pagopa/admissibility/connector/event/processor/AdmissibilityProcessorConfigFamilyTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/AdmissibilityEvaluatorMediatorServiceImplTest.java
> chore: Promote to UAT

- helm/values-uat.yaml
> chore: Setting MOCK url when integrating PDND in UAT

- src/main/java/it/gov/pagopa/admissibility/connector/soap/inps/service/IseeConsultationSoapClientImpl.java
- src/main/java/it/gov/pagopa/common/reactive/pdnd/service/BaseRestPdndServiceClient.java
- src/test/java/it/gov/pagopa/admissibility/connector/event/processor/AdmissibilityProcessorConfigTest.java
- src/test/java/it/gov/pagopa/admissibility/connector/rest/anpr/service/AnprC001RestClientImplIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/connector/soap/inps/service/IseeConsultationSoapClientImplIntegrationTest.java
- src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
> fix: fix PDND error handling

- pom.xml
- src/main/java/it/gov/pagopa/admissibility/connector/soap/inps/service/IseeConsultationSoapClientImpl.java
- src/main/java/it/gov/pagopa/common/reactive/pdnd/service/BaseRestPdndServiceClient.java
- src/test/java/it/gov/pagopa/admissibility/connector/event/processor/AdmissibilityProcessorConfigTest.java
- src/test/java/it/gov/pagopa/admissibility/connector/rest/anpr/service/AnprC001RestClientImplIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/connector/soap/inps/service/IseeConsultationSoapClientImplIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/AdmissibilityEvaluatorMediatorServiceImplTest.java
- src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
- src/test/java/it/gov/pagopa/common/utils/TestUtils.java
> fix: Release dev

- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/DummySpringRepository.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
- src/test/java/it/gov/pagopa/common/reactive/web/exception/MongoExceptionHandlerTest.java
> fix: IDP-2003 fix Mongo Retry When Anonymous Repo

- .grype.yaml
- Dockerfile
- pom.xml
> fix: fix CVE-2023-45853,CVE-2023-44487

- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java
- src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
> chore: removed jetbrain NotNull annotation usage

- pom.xml
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryer.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
> fix: IDP-2003 mongo retry when bulk writing

- src/main/java/it/gov/pagopa/admissibility/service/commands/CommandMediatorServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/service/commands/operations/DeleteInitiativeServiceImpl.java
- src/test/java/it/gov/pagopa/admissibility/connector/event/consumer/CommandConsumerConfigIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/service/commands/operations/DeleteInitiativeServiceImplTest.java
> fix: fix mongo cursor closed exception

- src/main/java/it/gov/pagopa/admissibility/service/commands/CommandMediatorServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/service/commands/operations/DeleteInitiativeServiceImpl.java
- src/test/java/it/gov/pagopa/admissibility/connector/event/consumer/CommandConsumerConfigIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/service/commands/operations/DeleteInitiativeServiceImplTest.java
> fix: fix mongo cursor closed exception (#219)

- .github/CODEOWNERS
- src/test/java/it/gov/pagopa/admissibility/BaseIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/connector/repository/CustomSequenceGeneratorOpsRepositoryImplTestIntegrated.java
- src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
- src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java
- src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java
- src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java
- src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java
- src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryTestIntegrated.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/EmbeddedMongodbTestReactiveClient.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/redis/config/EmbeddedRedisTestConfiguration.java
- src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports
- src/test/resources/mongodbEmbeddedDisabled.properties
> chore: IDP-2102 configuring a single mongodb instance for all tests

- .github/CODEOWNERS
- Dockerfile
- src/test/java/it/gov/pagopa/admissibility/BaseIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/connector/repository/CustomSequenceGeneratorOpsRepositoryImplTestIntegrated.java
- src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
- src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java
- src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java
- src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java
- src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java
- src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/BaseReactiveMongoRepositoryTestIntegrated.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/EmbeddedMongodbTestReactiveClient.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/redis/config/EmbeddedRedisTestConfiguration.java
- src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports
- src/test/resources/mongodbEmbeddedDisabled.properties
> chore: Release dev

- src/main/java/it/gov/pagopa/admissibility/mapper/Onboarding2EvaluationMapper.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/AdmissibilityEvaluatorMediatorServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/family/OnboardingFamilyEvaluationService.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/family/OnboardingFamilyEvaluationServiceImpl.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/AdmissibilityEvaluatorMediatorServiceImplTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/family/OnboardingFamilyEvaluationServiceTest.java
- Extend the end  date of onboarding in grace period (before publish ranking)
> fix: IDP-2136 [Analisi] Onboarding di un nucleo familiare su iniziativa a graduatoria tra fine periodo di adesione e pubblicazione

- pom.xml
- src/main/java/it/gov/pagopa/admissibility/mapper/Onboarding2EvaluationMapper.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/AdmissibilityEvaluatorMediatorServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/family/OnboardingFamilyEvaluationService.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/family/OnboardingFamilyEvaluationServiceImpl.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/AdmissibilityEvaluatorMediatorServiceImplTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/family/OnboardingFamilyEvaluationServiceTest.java
- src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
Promotion to UAT
- emptying kafka topic at each test + reduced common test timings
- onboarding family member in grace period of initiative ranking type
> feat: Promote to UAT

- src/main/java/it/gov/pagopa/admissibility/drools/transformer/extra_filter/ExtraFilter2DroolsUtils.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/check/OnboardingConsensusCheck.java
- src/main/java/it/gov/pagopa/common/config/HealthIndicatorLogger.java
> fix: fix sonar

- src/main/java/it/gov/pagopa/admissibility/service/onboarding/OnboardingContextHolderService.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/OnboardingContextHolderServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/evaluate/RuleEngineServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/utils/OnboardingConstants.java
- src/test/java/it/gov/pagopa/admissibility/connector/event/consumer/BeneficiaryRuleBuilderConsumerConfigIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/service/build/BeneficiaryRule2DroolsRuleImplTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/OnboardingContextHolderServiceImplTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/evaluate/RuleEngineServiceImplTest.java
> fix: IDP-2192 ONBOARDING_KO If Drools Not Ready

- src/main/java/it/gov/pagopa/admissibility/service/onboarding/OnboardingContextHolderService.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/OnboardingContextHolderServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/evaluate/RuleEngineServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/utils/OnboardingConstants.java
- src/test/java/it/gov/pagopa/admissibility/connector/event/consumer/BeneficiaryRuleBuilderConsumerConfigIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/service/build/BeneficiaryRule2DroolsRuleImplTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/OnboardingContextHolderServiceImplTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/evaluate/RuleEngineServiceImplTest.java
> fix: IDP-2192 ONBOARDING_KO If Drools Not Ready (#236)

- src/main/java/it/gov/pagopa/admissibility/service/onboarding/evaluate/RuleEngineServiceImpl.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/evaluate/RuleEngineServiceImplTest.java
> fix: IDP-2192 kieContainer ready logic simplified

- src/main/java/it/gov/pagopa/admissibility/connector/repository/DroolsRuleRepository.java
- src/main/java/it/gov/pagopa/admissibility/connector/repository/InitiativeCountersRepository.java
- src/main/java/it/gov/pagopa/admissibility/model/DroolsRule.java
- src/main/java/it/gov/pagopa/admissibility/service/build/BeneficiaryRule2DroolsRuleImpl.java
- src/main/java/it/gov/pagopa/admissibility/service/commands/operations/DeleteInitiativeServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/OnboardingContextHolderServiceImpl.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/ReactiveMongoRepositoryExt.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/ReactiveMongoRepositoryImpl.java
- src/test/java/it/gov/pagopa/admissibility/connector/event/consumer/CommandConsumerConfigIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/service/build/BeneficiaryRule2DroolsRuleImplTest.java
- src/test/java/it/gov/pagopa/admissibility/service/build/BeneficiaryRuleBuilderMediatorServiceTest.java
- src/test/java/it/gov/pagopa/admissibility/service/commands/operations/DeleteInitiativeServiceImplTest.java
> chore: logging drools rules deleted by command

- pom.xml
- src/main/java/it/gov/pagopa/admissibility/config/AdmissibilityErrorManagerConfig.java
- src/main/java/it/gov/pagopa/admissibility/controller/AdmissibilityControllerImpl.java
- src/main/java/it/gov/pagopa/admissibility/utils/OnboardingConstants.java
- src/main/java/it/gov/pagopa/common/web/exception/ErrorManager.java
- src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
- src/test/java/it/gov/pagopa/common/reactive/web/exception/MongoExceptionHandlerTest.java
IDP-2090 application specific error codes
> feat: IDP-2090 application specific error codes

- src/main/java/it/gov/pagopa/admissibility/config/AdmissibilityErrorManagerConfig.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/evaluate/RuleEngineServiceImpl.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/OnboardingContextHolderServiceIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/evaluate/RuleEngineServiceImplTest.java
> fix: IDP-2223 fix empty Drools Container handling

- .grype.yaml
- Dockerfile
- pom.xml
- src/test/java/it/gov/pagopa/admissibility/BaseIntegrationTest.java
- src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
> fix: IDP-2196 fix Cve

- src/test/java/it/gov/pagopa/admissibility/connector/event/consumer/BeneficiaryRuleBuilderConsumerConfigIntegrationTestDeprecated.java
- src/test/java/it/gov/pagopa/admissibility/connector/event/consumer/CommandConsumerConfigIntegrationTestDeprecated.java
- src/test/java/it/gov/pagopa/admissibility/connector/event/processor/AdmissibilityProcessorConfigFamilyTestDeprecated.java
- src/test/java/it/gov/pagopa/admissibility/connector/event/processor/AdmissibilityProcessorConfigRankingTestDeprecated.java
- src/test/java/it/gov/pagopa/admissibility/connector/event/processor/AdmissibilityProcessorConfigTestDeprecated.java
- src/test/java/it/gov/pagopa/admissibility/connector/rest/mock/FamilyMockRestClientImplTestDeprecated.java
- src/test/java/it/gov/pagopa/admissibility/connector/soap/inps/service/IseeConsultationSoapClientImplIntegrationTestDeprecated.java
- src/test/java/it/gov/pagopa/admissibility/connector/soap/inps/service/IseeConsultationSoapClientImplSSLKOTest.java
- src/test/java/it/gov/pagopa/admissibility/service/CriteriaCodeServiceIntegrationTestDeprecated.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/AuthoritiesDataRetrieverServiceIntegrationTestDeprecated.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/OnboardingContextHolderServiceIntegrationTestDeprecated.java
> fix: [IDP-2288] Changed test class name

- src/main/java/it/gov/pagopa/admissibility/config/InpsConfiguration.java
- src/main/java/it/gov/pagopa/admissibility/config/KafkaConfiguration.java
- src/main/java/it/gov/pagopa/admissibility/connector/soap/inps/config/InpsClientConfig.java
- src/main/java/it/gov/pagopa/admissibility/drools/transformer/extra_filter/filter/op/ScalarOpValueBuilder.java
- src/main/java/it/gov/pagopa/admissibility/mapper/AutomatedCriteria2ExtraFilterMapper.java
- src/main/java/it/gov/pagopa/admissibility/model/OnboardingFamilies.java
- src/main/java/it/gov/pagopa/admissibility/service/AdmissibilityErrorNotifierService.java
- src/main/java/it/gov/pagopa/admissibility/service/AdmissibilityErrorNotifierServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/evaluate/RuleEngineServiceImpl.java
- src/main/java/it/gov/pagopa/common/kafka/service/ErrorNotifierService.java
- src/main/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceImpl.java
- src/main/java/it/gov/pagopa/common/reactive/kafka/consumer/BaseKafkaConsumer.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/ReactiveMongoRepositoryExt.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/ReactiveMongoRepositoryImpl.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
- src/main/java/it/gov/pagopa/common/utils/CommonUtilities.java
- src/test/java/it/gov/pagopa/admissibility/connector/soap/inps/service/IseeConsultationSoapClientImplTest.java
- src/test/java/it/gov/pagopa/admissibility/drools/transformer/extra_filter/filter/op/ScalarOpValueBuilderTest.java
- src/test/java/it/gov/pagopa/admissibility/service/AdmissibilityErrorNotifierServiceImplTest.java
- src/test/java/it/gov/pagopa/admissibility/service/InpsConfigurationTest.java
- src/test/java/it/gov/pagopa/admissibility/service/KafkaConfigurationTest.java
- src/test/java/it/gov/pagopa/admissibility/service/commands/operations/DeleteInitiativeServiceImplTest.java
- src/test/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/ReactiveMongoRepositoryImplTest.java
- Removed suppress warning
- Added configuration class
> fix: IDP-2359 remove warning suppress and code-smell

- src/main/java/it/gov/pagopa/admissibility/config/InpsConfiguration.java
- src/main/java/it/gov/pagopa/admissibility/config/KafkaConfiguration.java
- src/main/java/it/gov/pagopa/admissibility/connector/soap/inps/config/InpsClientConfig.java
- src/main/java/it/gov/pagopa/admissibility/drools/transformer/extra_filter/filter/op/ScalarOpValueBuilder.java
- src/main/java/it/gov/pagopa/admissibility/mapper/AutomatedCriteria2ExtraFilterMapper.java
- src/main/java/it/gov/pagopa/admissibility/model/OnboardingFamilies.java
- src/main/java/it/gov/pagopa/admissibility/service/AdmissibilityErrorNotifierService.java
- src/main/java/it/gov/pagopa/admissibility/service/AdmissibilityErrorNotifierServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/evaluate/RuleEngineServiceImpl.java
- src/main/java/it/gov/pagopa/common/kafka/service/ErrorNotifierService.java
- src/main/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceImpl.java
- src/main/java/it/gov/pagopa/common/reactive/kafka/consumer/BaseKafkaConsumer.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/ReactiveMongoRepositoryExt.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/ReactiveMongoRepositoryImpl.java
- src/main/java/it/gov/pagopa/common/reactive/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
- src/main/java/it/gov/pagopa/common/utils/CommonUtilities.java
- src/test/java/it/gov/pagopa/admissibility/connector/soap/inps/service/IseeConsultationSoapClientImplTest.java
- src/test/java/it/gov/pagopa/admissibility/drools/transformer/extra_filter/filter/op/ScalarOpValueBuilderTest.java
- src/test/java/it/gov/pagopa/admissibility/service/AdmissibilityErrorNotifierServiceImplTest.java
- src/test/java/it/gov/pagopa/admissibility/service/InpsConfigurationTest.java
- src/test/java/it/gov/pagopa/admissibility/service/KafkaConfigurationTest.java
- src/test/java/it/gov/pagopa/admissibility/service/commands/operations/DeleteInitiativeServiceImplTest.java
- src/test/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceTest.java
- src/test/java/it/gov/pagopa/common/reactive/mongo/ReactiveMongoRepositoryImplTest.java
- Removed suppress warning
- Added configuration class
> fix: Promote to UAT

- src/test/java/it/gov/pagopa/admissibility/BaseIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/connector/rest/anpr/service/AnprC001RestClientImplIntegrationTest.java
- src/test/java/it/gov/pagopa/admissibility/connector/rest/anpr/service/AnprC001RestClientSSLKOTest.java
- src/test/java/it/gov/pagopa/common/reactive/wireMock/BaseWireMockTest.java
- src/test/resources/stub/mappings/anpr/0_c020ResidenceAssessment.json
- src/test/resources/stub/mappings/anpr/c020ResidenceAssessmentInvalidRequest.json
- src/test/resources/stub/mappings/anpr/c020ResidenceAssessmentNotFound.json
- src/test/resources/stub/mappings/anpr/c020ResidenceAssessmentTooManyRequests.json
> fix: context configuration test

- helm/values-prod.yaml
- helm/values-uat.yaml
> feat: added secret values uat

- src/main/java/it/gov/pagopa/admissibility/model/AnprInfo.java
- src/main/java/it/gov/pagopa/admissibility/model/Child.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/family/FamilyDataRetrieverFacadeServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/pdnd/FamilyDataRetrieverService.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/pdnd/FamilyDataRetrieverServiceImpl.java
- src/main/java/it/gov/pagopa/admissibility/utils/Utils.java
- src/main/java/it/gov/pagopa/common/reactive/pdnd/service/BaseRestPdndServiceClient.java
- src/main/java/it/gov/pagopa/common/reactive/pdv/service/UserFiscalCodeRestClientImpl.java
- src/main/java/it/gov/pagopa/common/utils/CommonUtilities.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/family/FamilyDataRetrieverFacadeServiceTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/pdnd/FamilyDataRetrieverServiceTest.java
> feat: Idp 2614 add child info on db

- src/main/java/it/gov/pagopa/admissibility/service/onboarding/pdnd/FamilyDataRetrieverServiceImpl.java
> fix: method signature change

- src/test/java/it/gov/pagopa/admissibility/service/onboarding/pdnd/FamilyDataRetrieverServiceTest.java
> FIX: add jUnit

- src/main/java/it/gov/pagopa/admissibility/service/onboarding/pdnd/FamilyDataRetrieverServiceImpl.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/pdnd/FamilyDataRetrieverServiceTest.java
- Added born date check before add element in child list
> fix: Child list fix

- src/main/java/it/gov/pagopa/admissibility/model/AnprInfo.java
- src/main/java/it/gov/pagopa/admissibility/service/onboarding/pdnd/FamilyDataRetrieverServiceImpl.java
> feat: Add underAgeNumber in AnprInfo

- src/main/java/it/gov/pagopa/admissibility/service/onboarding/pdnd/FamilyDataRetrieverServiceImpl.java
> fix: under18 fix

- src/main/java/it/gov/pagopa/common/reactive/pdnd/service/BaseRestPdndServiceClient.java
> fix: log delete

- .github/workflows/anchore.yml
- .github/workflows/flow-docker-snapshot.yml
- .github/workflows/release.yml
- src/main/java/it/gov/pagopa/admissibility/utils/Utils.java
> chore: [IDP-2677] add release workflows for new CI/CD processes

- .github/workflows/release.yml
- .github/workflows/snapshot-docker.yml
- src/main/java/it/gov/pagopa/admissibility/controller/AdmissibilityControllerImpl.java
> chore: add release and snapshot-docker file

- src/main/java/it/gov/pagopa/admissibility/controller/AdmissibilityControllerImpl.java
> fix: update release version

- src/main/java/it/gov/pagopa/admissibility/dto/onboarding/EvaluationDTO.java
- src/main/java/it/gov/pagopa/admissibility/dto/onboarding/OnboardingDTO.java
- src/main/java/it/gov/pagopa/admissibility/mapper/Onboarding2EvaluationMapper.java
- src/main/java/it/gov/pagopa/admissibility/mapper/Onboarding2OnboardingDroolsMapper.java
- src/test/java/it/gov/pagopa/admissibility/drools/transformer/extra_filter/ExtraFilter2DroolsUtilsTest.java
- src/test/java/it/gov/pagopa/admissibility/mapper/Onboarding2EvaluationMapperTest.java
- src/test/java/it/gov/pagopa/admissibility/mapper/Onboarding2OnboardingDroolsMapperTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/check/OnboardingConsensusCheckTest.java
- src/test/java/it/gov/pagopa/admissibility/service/onboarding/check/OnboardingInitiativeCheckTest.java
Adding userMail, channel, and verifyIsee fields to EvaluationDTO, OnboardingDTO, and the related mapper
> feat: [UPBE-182] adeguamento evaluationDTO
